/* Pagination Controller */

app.controller('paginationCtrl', ['$scope', '$timeout', function($scope, $timeout) {
	$scope.input = {
	    "articles": [
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        },
	        {
	            "article": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla venenatis congue finibus. Cras justo risus, faucibus nec enim quis, lobortis porta purus. Maecenas tincidunt dui vitae elit consequat convallis. Nam condimentum iaculis nibh. Integer consequat felis ut ultrices finibus. Quisque hendrerit condimentum laoreet. Mauris ullamcorper vitae nisl sed vehicula. Mauris rutrum, nulla eget placerat iaculis, mi magna interdum urna, quis semper tellus neque vestibulum diam. Ut non convallis nibh. Nunc mi diam, egestas sit amet sollicitudin at, finibus id diam. Proin diam massa, consequat sed mauris non, auctor ullamcorper massa. Nullam id rhoncus ligula. Sed egestas mauris a mauris dapibus consectetur."
	        }
	    ]
	};

	$scope.inputHTML = {
	    "articles": [
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        },
	        {
	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a></div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	        }
	    ]
	}; 

	// $timeout(function() {
	// 	$scope.inputHTML = {
	// 	    "articles": [
	// 	        {
	// 	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a>1</div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	// 	        },
	// 	        {
	// 	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a>2</div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	// 	        },
	// 	        {
	// 	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a>3</div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	// 	        },
	// 	        {
	// 	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a>4</div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	// 	        },
	// 	        {
	// 	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a>5</div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	// 	        },
	// 	        {
	// 	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a>6</div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	// 	        },
	// 	        {
	// 	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a>7</div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	// 	        },
	// 	        {
	// 	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a>8</div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	// 	        },
	// 	        {
	// 	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a>9</div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	// 	        },
	// 	        {
	// 	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a>10</div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	// 	        },
	// 	        {
	// 	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a>11</div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	// 	        },
	// 	        {
	// 	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a>12</div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	// 	        },
	// 	        {
	// 	            "article": "<div class='result'><div  class='contentHeading'><a href=''>[Archived] ESX Server 3.0.2, Patch ESX-1002425; Updates to hostd-exs(1002425)</a>13</div><div  class='contentDesc'>...Flushing ice devices:[device names]System halted. Deployment Consideration. A restart of the host engine is required  after applying  this patch. ...</div><div class='contentLink'><a href=''>http://kb.vmware.com/kb/1096733</a></div><div class='contentMeta'><div class='star_1 ratings_vote'></div><div class='star_2 ratings_vote'></div><div class='star_3 ratings_stars'></div><div class='star_4 ratings_stars'></div><div class='star_5 ratings_stars'></div><span class='rate'>&nbsp;2</span> Rating |  Author: <span class='author'>Shibu John(sJohn)</span> | Created date: <span class='dateCreated'>10/28/10</span></div></div>"
	// 	        }
	// 	    ]
	// 	};
	// }, 5000); 

}]);